auth_enabled: false

server:
  http_listen_port: 3100

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /var/loki/chunks

compactor:
  working_directory: /var/loki/compactor
  retention_enabled: true

limits_config:
  retention_period: 168h   # 7 days
